import type { Metadata } from "next";
import "./globals.css"

import SiteHeader from "@/components/site-header";
import SiteFooter from "@/components/site-footer";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
   <html lang="en" className="antialiased" suppressHydrationWarning>
         <body className="min-h-screen bg-background text-foreground">
        <Suspense fallback={<div>Loading...</div>}>
          
          <main className="min-h-[80svh]">{children}</main>
        
        </Suspense>
      
      </body>
    </html>
  )
}
